- name: Test
  hosts: buildfarm
  tasks:
    - name: Test all branches
      ansible.builtin.shell:
        cmd: ./run_branches.pl --force --run-all --test --verbose
        chdir: "{{ install_path }}/build-farm-{{ build_farm_version }}-{{ inventory_hostname }}"
      register: output
    - name: Display output
      ansible.builtin.debug:
        var: output
