- name: Enable automatic building with cron
  hosts: buildfarm
  tasks:
    - name: Set cron
      ansible.builtin.cron:
        name: "{{ inventory_hostname }}"
        job: "cd {{ install_path }}/{{ build_farm_version }}-{{ inventory_hostname }} && perl ./run_branches.pl --run-all"
        hour: "{{ hour }}"
        minute: "{{ minute }}"
      when: hour is defined and minute is defined
