# Global configuration for all build farm animals

BUILD_FARM_VERSION="20"
EMAIL="markwkm@gmail.com"
MINUTE=30
BUILD_ROOT='\$confdir/buildroot'
GLOBAL_LOCK_DIR="/tmp"
DEFAULT_CONFIG_OPTS="--enable-cassert --enable-debug --enable-nls --with-perl --with-python --with-tcl --with-gssapi --with-openssl --with-ldap --with-libxml --with-libxslt"
